#include"define.h"
int map[MAX_X][MAX_Y];//cout<<symbol[map[x][y]];
bool mapWarFog[MAX_X][MAX_Y];
char symbol[30] = { " @X.#MEI|-0123456789ST" };
int x[MAPNUM], y[MAPNUM], r[MAPNUM];
int monster_num = MONSTERNUM;
int monster_x[MONSTERNUM];
int monster_y[MONSTERNUM];
int monster_HP[MONSTERNUM];
int monster_attack[MONSTERNUM];
int monster_alive[MONSTERNUM];
int prop_num = PROPNUM;
int prop_attack[PROPNUM];
int prop_x[PROPNUM];
int prop_y[PROPNUM];
int actor_HP;
int actor_Money;
int actor_x;
int actor_y;
int actor_attack;
int necklice_x;
int necklice_y;
bool mainLoop;
bool gameLoop;
bool alive;
int layer;
int transport_x;
int transport_y;
int monsternum = 0;
char keyBroadInput;